### ISSUE TITLE
Using Testee programmatically returns empty "tests" array

### ISSUE THREAD

**Issue by leoj3n** [bitovi/testee#111]
Mocha using Testee to run QUnit tests programmatically.... Trying to get passed QUnits....

```
QUnit "test/resizes/resizes-test.html" on Firefox 52.0.0 / Mac OS X 10.12.0:

    bit-docs-tag-demo
      basics
        ✓ there are three tabs
        ✓ there are three tab contents


  2 passing (6s)

---------- console.dir(results); --------------

[ { status: 'finished',
    file: 'http://localhost:3996/test/resizes/resizes-test.html?__token=n3p2aa',
    id: '319d1c8940a86b1f1b5d1371e91a2968',
    environment: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0',
    runner: 'QUnit',
    time: 1493049277592,
    failed: 0,
    passed: 2,
    total: 2,
    runtime: 592,
    tests: [] } ]
```

Should this contain something, like more information about the assertions that passed?

```
    tests: [] 
```

**Comment by andrejewski** [comment]
@leoj3n What `results` represents in the code is the very last "packet" of communication from the browser's Testee client. I agree it seems out of place to have a useless array, however in my experience with people using test runners they are not too concerned with single assertions, more that `failed === 0`. To my knowledge this result object is undocumented, so I have two options:
- Do nothing, maybe delete the `tests` array from the output result
- Create a well defined output result with a strong data schema for representing these individual assertions.

I think the direction we go will be based on user feedback. I do not want to write something no one has asked for and to my knowledge no one has asked for programmatic access to assertion results.

Please open a new issue (anyone), if you need this new feature. Closing this mystery as solved.
