### ISSUE TITLE
Suppress "[browser] not available"

### ISSUE THREAD

**Issue by stevenvachon** [bitovi/testee#121]
Optionally. It's nice to have a local `npm test` that tests whatever browsers are available on the system:
```shell
testee test.html --browsers=chrome,edge,firefox,ie,safari
```

**Comment by andrejewski** [comment]
Could you elaborate on the use case? Personally, if a browser is not available I want to know and having this *optionally* supported would lead to a lot of confusion I think. Having an option like below might be better to do, though I have never wanted this myself.

```sh
testee test.html --all-browsers
```

**Comment by stevenvachon** [comment]
Yeah, something like that or `--available-browsers` would be better, like [karma-detect-browsers](https://npmjs.com/karma-detect-browsers).

**Comment by andrejewski** [comment]
Closing in favor of #150, as I think it articulates the issue better.
