### ISSUE TITLE
Add support for headless chrome?

### ISSUE THREAD

**Issue by leoj3n** [bitovi/testee#127]
https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by chasenlehara** [comment]
I wonder how easily we could support this. It looks like [launchpad supports launching browsers with arguments](https://github.com/bitovi/launchpad/pull/42), so we just need to add support from that within Testee (if we don’t already).

**Comment by Alfredo-Delgado** [comment]
@leoj3n What kind of problem are you encountering when trying to run chrome headless?

**Comment by leoj3n** [comment]
> What kind of problem are you encountering when trying to run chrome headless?

Lack of documentation if it's already possible.

**Comment by Alfredo-Delgado** [comment]
The current [config api example](https://github.com/bitovi/testee#configuration-api) mentions chrome, but it doesn't include an example of passing in additional arguments to a browser. This is necessary to [make Chrome run headless](https://developers.google.com/web/updates/2017/04/headless-chrome).

e.g.
```json
{
  "browsers": [
    {
      "browser": "chrome",
      "args": [
        "--headless",
        "--disable-gpu",
        "--remote-debugging-port=9222"
      ]
    }
  ]
}
```

I think that's a good place to update the docs.

**Comment by andrejewski** [comment]
@Alfredo-Delgado We do have documentation in https://github.com/bitovi/testee#browsers. Perhaps the Chrome Headless use case is so common it may deserve its own section so people can find it easier.

**Comment by Alfredo-Delgado** [comment]
That works, too. I was thinking along the same lines of it being a common use case, hence why I thought _A simple, local browser config (JSON) example with mostly default values could look like_ was the best place for it. I'd say definitely also update https://github.com/bitovi/testee#browsers to include the extra headless args.

**Comment by andrejewski** [comment]
Sure; I'll update both later today, no reason not to have one and then no reason not to have both for doc consistency.

**Comment by matthewp** [comment]
I think it's common enough that it might deserve it's own `browser` type.

**Comment by Alfredo-Delgado** [comment]
@matthewp That doesn't conflict with updating the documentation. It sounds like a nice enhancement.

We also have the opportunity to further enhance documentation by capturing how to install chromium via npm and configure testee to run that instance. @nlundquist showed me how he went about it in one of his projects and just a few hours later, unprompted, it came up in my current project.

**Comment by matthewp** [comment]
Agreed, don't think documenting the current method should be blocked.

**Comment by andrejewski** [comment]
I think for now documentation of the flags is good enough. To create a new browser type is to really create an alias here in Testee or a more powerful launcher in Launchpad, which is worth discussing.

Regarding *Chromium*, I am interested in what that setup is. Headless and this Chromium install thing could probably fill a whole new section. As long as that alone doesn't get too blog-post-worthy.
