### ISSUE TITLE
Browserstack IE < 10 seems not to be working

### ISSUE THREAD

**Issue by tekny** [bitovi/testee#44]
I assume it's because of IE < 10 doesn't support websockets.

**Comment by daffl** [comment]
It should work with anything that's supported by socket.io. I just tested with IE9 and 8 and got reports back. How does your setup look like?

**Comment by tekny** [comment]
Using OS X 10.10
Running testee as a grunt task.
```javascript
browserstack : {
    options: {
        launch: {
            type: "browserstack",
            username: process.env.BROWSERSTACK_USER,
            password: process.env.BROWSERSTACK_PASSWORD,
            version: 2
        },

        browsers: [{
            os: "win",
            browser: "ie",
            version : "9.0"
        }],

        tunnel: {
          "type": "browserstack",
          "key": process.env.BROWSERSTACK_PASSWORD
        },
    },

    src : ['qunit/index.html']
}
```

### [Debug log on gist (too large to post it here)](https://gist.github.com/tekny/295e03eb389ef3c87ba5)

### And Browserstack VM screenshot: 
![ie9](https://cloud.githubusercontent.com/assets/1202320/6027149/d878b95c-abe8-11e4-9943-292048f53067.png)


IE10 and other browsers work fine.

**Comment by daffl** [comment]
Thanks for the detailed report. I will look into it and see what is happening. It could be an issue with Browserstack and what Socket.IO uses as a websocket fallback in IE8.

**Comment by stevenvachon** [comment]
Tested with CLI config file and programmatic API in IE9 and it worked fine.

**Comment by andrejewski** [comment]
@tekny has time made this issue disappear? Please let me know, otherwise I can close this issue based on @stevenvachon recent comment.
