### ISSUE TITLE
Unable to run tests when root is set to a URL path in Grunt Task

### ISSUE THREAD

**Issue by dannyfinks** [bitovi/testee#45]
I may be missing something here, but I am getting the "Warning: No file passed to Testee task" error even though I have a file that shows up when I run the task in verbose mode. Is it perhaps not possible to use a webroot for the grunt task? I am successfully able to run the same root/src type of set up from the command line option. 

This is my grunt setup:

``` javascript
testee: {
            options: {
                reporter: 'Spec',
                root: 'http://test:test@testing.com/builds'
            },
            coverage: {
                options: {
                    browsers: 'chrome',
                },
                src: 
                    ['archive/test/api-uni-test.html']
            },
}
```

**Comment by andrejewski** [comment]
This is addressed in the new [`grunt-testee` project](https://github.com/bitovi/grunt-testee), you may use a remote URL as root.
