### ISSUE TITLE
fail fast if a file doesn't exist

### ISSUE THREAD

**Issue by kevinbarabash** [bitovi/testee#48]
Currently `testee hello_world.html` will wait to timeout if `hello_world.html` doesn't exist.  It would be nice if testee would fail fast (or at least have the option to).  In the case where multiple files are provided and some are valid and some are not, it should probably check all the paths first and fail (with an appropriate message) if any of them don't exist.

**Comment by daffl** [comment]
We could add a quick check if a local file exists. It wouldn't work for proxied files on remote servers though.

**Comment by kevinb7** [comment]
Also, this isn't a huge priority so whenever you get to it.
