### ISSUE TITLE
Testee isn't closing all the tabs after it finishes.

### ISSUE THREAD

**Issue by marshallswain** [bitovi/testee#53]
Testee isn't putting away its tabs after it's done playing.  See the screenshot showing a finished `grunt test` and the tabs in the browser are left open. (they start with "localhost")

![screen shot 2015-08-27 at 12 13 11 pm 1](https://cloud.githubusercontent.com/assets/128857/9526238/15965c18-4cb6-11e5-95c5-1111bc05c257.png)

**Comment by daffl** [comment]
That only happens if the browser is already open - it really shouldn't close it. The solution for now is to use a different browser (Canary or Firefox if you are using Chrome). I'm still not sure how to start anonymous new browsers.

**Comment by daffl** [comment]
Related: https://github.com/ekryski/launchpad/issues/11

**Comment by andrejewski** [comment]
This is being worked on in Launchpad, it's not a Testee issue unless the solution is to expose configuration options for Testee to utilize. Closing this as that is not going to be the case for awhile, if ever.
