### ISSUE TITLE
More Coverage Options

### ISSUE THREAD

**Issue by phillipskevin** [bitovi/testee#55]
The html reporter that Karma has is really useful for finding missed lines and branches. Since they're also using Istanbul, it shouldn't be too difficult to get this same reporter working in Testee. There are many other reporters and additional coverage options that might be useful for people.

**Comment by daffl** [comment]
The `coverage` options should allow different reporters. Output options (paths) might be a problem at the moment but it should be easily solvable by using those options and set them in the Istanbul collector at https://github.com/HackerYou/SlackerYou.

**Comment by daffl** [comment]
I think this has been closed via #57
