### ISSUE TITLE
Remote URLs aren't considered in Grunt task

### ISSUE THREAD

**Issue by alexisabril** [bitovi/testee#59]
Remotely hosted urls are not considered in the grunt task logic. grunt.files.expand and all the logic thereafter assume a local file is passed. If a remote url is passed, the files array is empty and the warning is thrown.

CLI version does not make this assumption.

**Comment by daffl** [comment]
The Grunt task could just fall back to a seoarate `files` option if it is empty.

**Comment by andrejewski** [comment]
This is addressed in the new [`grunt-testee` project](https://github.com/bitovi/grunt-testee), you may pass remote URLs just like regular local files.
