### ISSUE TITLE
Add Gulp task to ReadMe

### ISSUE THREAD

**Issue by phillipskevin** [bitovi/testee#62]
```
gulp.task('test', function(){
    return testee.test(['test/test.html'], 'phantom', {
        reporter: 'Spec'
    });
});
```

**Comment by daffl** [comment]
I just realized it doesn't have a section on programmatic use anyway so that is definitely good to add.

**Comment by phillipskevin** [comment]
Thanks to @ccummings for posting it. I can add it to the readme when I have a couple minutes.
