### ISSUE TITLE
Add support for ES6 and Code Coverage

### ISSUE THREAD

**Issue by phillipskevin** [bitovi/testee#65]
Some ES6 syntax breaks Istanbul instrumentation.

**Comment by phillipskevin** [comment]
Switching to [isparta](https://github.com/douglasduteil/isparta) is simple and allows coverage to work on the project I was having trouble with. Should this be done by default whenever running with coverage, or do we want to allow the user to choose which coverage instrumentation to use? If a project is already running testee with their transpiled files, they might not want to transpile again.

/cc @daffl

**Comment by daffl** [comment]
We should probably make it configurable. It looks like this one only works with Babel?

**Comment by phillipskevin** [comment]
Right, it just runs babel and then Istanbul. I haven't done too much research on other alternatives to isparta.

**Comment by justinbmeyer** [comment]
Can someone walk me through this?

There's steal, testee, instanbul, and babel.

What does what, where do things go wrong?  

My assumption on a "perfect" solution would be `steal` uses `babel` and an `instanbul` plugin to `babel` to transpile all code to be instrumented.

Testee would just run the tests as normal, but be looking out for some signal that there's code coverage information.

**Comment by daffl** [comment]
What it currently does is instrument the JS files on the server before sending them. This works for any ES5 JavaScript file (also with anything like Browserify, Webpack and server side Babel that builds things first).

The problem is that the instrumentation even with the 1.0-beta Istanbul that supposedly works with ES6 as far as I could get it to work creates output that does not work with Steal when it loads the individual files on the client.

**Comment by ccummings** [comment]
A [new babel plugin](https://www.npmjs.com/package/babel-plugin-__coverage__) exists that generates a __coverage__ variable for es6 code. Not sure if it suffers from the same problem as istanbul today.

**Comment by matthewp** [comment]
I'm confused as to how Instanbul instruments on the server. Does it overwrite files? Like if I have a file foo.js it changes the contents of foo.js on my filesystem (and presumably restores it back afterwards)? Is this what happens?

**Comment by daffl** [comment]
It instruments them on the fly with [connect-injector](https://github.com/daffl/connect-injector) just like when it adds the client script to HTML test files.

**Comment by matthewp** [comment]
I see, so if you are using a bundler the source has already been transpiled, but in the case of Steal it is has not.

Would it be possible to allow the user to hook into this pipeline so they could insert their own transpilation prior to the instrumentation step? That way you could possibly transpile just the `import` statements to commonjs before instanbul gets to it.

**Comment by matthewp** [comment]
Talking about this problem a bit more, it feels like me the solution would be to use their Babel plugin (and only their Babel plugin) to add the coverage code on the fly, the same way that Testee currently adds the coverage code using the old Istanbul API (which internally uses an old Esprima version).

This would be a minimal change, only changing how [coverage is added](https://github.com/bitovi/testee/blob/e8610368469c3e294a89d087b3213be816acc299/lib/host/coverage.js#L31)

Note: this would only run the istanbul babel plugin. It wouldn't transpile `class` syntax or import/export or anything else.

**Comment by phillipskevin** [comment]
I'm going to give this a try.

**Comment by pmgmendes** [comment]
E foi mesmo o empate :)

**Comment by phillipskevin** [comment]
This is closed in [v0.4.0](https://github.com/bitovi/testee/releases/tag/v0.4.0). Nice work @andrejewski finishing this off!
