### ISSUE TITLE
Project page appears to be out of date with latest

### ISSUE THREAD

**Issue by akagomez** [bitovi/testee#66]
The `-v` option exists on the project page, but not in the README.

![](https://i.imgur.com/Oz7tRHe.png)
http://daffl.github.io/testee.js/

![](https://i.imgur.com/rLbvBpC.png)
https://github.com/bitovi/testee/blob/master/README.md

**Comment by daffl** [comment]
What does it do? I don't see it defined in https://github.com/bitovi/testee/blob/master/bin/testee#L10 so I'd assume it's the same as `-V` and `--version` (which is what Commander provides)?

**Comment by akagomez** [comment]
I'm not sure. I don't have a version of testee that works with `-v`: 

```
totes:web akagomez$ ./node_modules/testee/bin/testee -v -l funcunitEndo.html

  error: unknown option `-v'
```

**Comment by daffl** [comment]
What do you mean with project page? Is the homepage still up? I thought I disabled it.

**Comment by akagomez** [comment]
Seems up to me: http://daffl.github.io/testee.js/

**Comment by daffl** [comment]
I removed the gh-pages branches and the old page (apparently the GitHub pages stays after you remove the repository). The Readme should be the only source of information now (and hopefully up to date).
