### ISSUE TITLE
Gulp run of testee not working

### ISSUE THREAD

**Issue by RALifeCoach** [bitovi/testee#72]
My simple gulp file is:
```javascript
var gulp = require('gulp');
var testee = require('testee');

gulp.task('test', function() {
    return testee.test(['/site-html/test.html'], 'chrome', {
        reporter: 'Spec'
    });
});
```
When I run, the browser opens and I get the following message: Cannot GET /site-html/test.html?__token=g7arh2

**Comment by matthewp** [comment]
Gulp has nothing to do with this. I'm guessing `/site-html/test.html` is not a file that exists on your file system. Maybe you meant `site-html/test.html`.

**Comment by RALifeCoach** [comment]
@matthewp I removed the leading slash and I am getting the same results. The browser is available and I have tried running the test manually without success. I then ran outside of gulp (which worked), copied the url, ran in gulp, pasted the url - still no change.

**Comment by matthewp** [comment]
Wait, so you're saying you have this?

```js
var testee = require('testee');

testee.test(['/site-html/test.html'], 'chrome', {
  reporter: 'Spec'
});
```

and that works?

**Comment by daffl** [comment]
You may have to specify the root folder. Does it run from the command line with `testee site-html/test.html --browsers firefox --reporter Spec`?

**Comment by RALifeCoach** [comment]
When I run "testee test.html --browsers chrome" from the command line it works (with current directory being site-html). And when I look at the browser while the test is running, the url is localhost:3996/site-html/test.html - exactly the same url as I see then I run it using gulp. However, as stated above, when running in gulp the url generates a GET error.

**Comment by RALifeCoach** [comment]
My apologies to you both. When I removed the site-html/ from the source file - it ran just fine.
