### ISSUE TITLE
Testee not closing nw.js when tests are complete

### ISSUE THREAD

**Issue by ericcarino** [bitovi/testee#88]
We have an nw.js based application.  On Mac, we recently changed the bundle name of the application.  This has caused testee to hang for some reason.  Once the tests have completed, testee doesn't close nw.js, thus the "hang".

I noticed if I have multiple copies of the application on my system, some have the old bundle name, others with the new, then this causes testee not able to close nw.js.  To workaround, I remove all of the applications with the old bundle name, update Mac's Launch Services database, and that resolves the issue.  This process is fine for developer machines.  This process is not fine for our build machines, as it has to be able to build versions of our application with both the old & new bundle name.

**Comment by andrejewski** [comment]
Issue moved to [bitovi/launchpad #87](https://github.com/bitovi/launchpad/issues/87) via [**ZenHub**](https://www.zenhub.com/)
