### ISSUE TITLE
XUnit reporter error

### ISSUE THREAD

**Issue by vobujs** [bitovi/testee#93]
testee 0.3.0-pre.2
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
macOS 10.12.1

When running testee with the XUnit reporter (no matter command-line or grunt task), the following error occurs:

testee test/unit/unitTests.qunit.html --reporter XUnit
/<snip>/node_modules/testee/node_modules/mocha/lib/reporters/xunit.js:44
if (options.reporterOptions && options.reporterOptions.output) {
^

TypeError: Cannot read property 'reporterOptions' of undefined
at new XUnit (/<snip>/node_modules/testee/node_modules/mocha/lib/reporters/xunit.js:44:14)
...

Commenting out lines 44-50 in /<snip>/node_modules/testee/node_modules/mocha/lib/reporters/xunit.js makes it work again.

**Comment by eintrachtfan** [comment]
I had to change line 44 from:

if (options.reporterOptions && options.reporterOptions.output) {

to

if (options && options.reporterOptions && options.reporterOptions.output) {

**Comment by vobujs** [comment]
the base error was in mocha's XUnit reporter and got fixed here: https://github.com/mochajs/mocha/pull/2585

So as soon as a new mocha version gets released, could you @daffl please bump the mocha dep in package.json?

**Comment by daffl** [comment]
Closed via #98
